export const cardArr = [
  {
    id: 0,
    title: 'Пвх материал 2й сорт',
    price: '170 ₽',
    address: 'Казань, р-н Вахитовский',
    date: '10 июля 11:39',
    image: '/images/product.png',
  },
  {
    id: 1,
    title: 'Первый товар',
    price: '171 ₽',
    address: 'Казань, р-н Вахитовский',
    date: '10 июля 11:39',
    image: '/images/product.png',
  },
  {
    id: 2,
    title: 'Второй товар',
    price: '172 ₽',
    address: 'Казань, р-н Вахитовский',
    date: '10 июля 11:39',
    image: '/images/product.png',
  },
  {
    id: 3,
    title: 'Третий товар',
    price: '173 ₽',
    address: 'Казань, р-н Вахитовский',
    date: '10 июля 11:39',
    image: '/images/product.png',
  },
  {
    id: 4,
    title: 'Четвертый товар',
    price: '174 ₽',
    address: 'Казань, р-н Вахитовский',
    date: '10 июля 11:39',
    image: '/images/product.png',
  },
  {
    id: 5,
    title: 'Пятый товар',
    price: '175 ₽',
    address: 'Казань, р-н Вахитовский',
    date: '10 июля 11:39',
    image: '/images/product.png',
  },
  {
    id: 6,
    title: 'Шестой товар',
    price: '176 ₽',
    address: 'Казань, р-н Вахитовский',
    date: '10 июля 11:39',
    image: '/images/product.png',
  },
];
